insert into author(id, first_name, last_name) values(1, 'Albert', 'Camus');
insert into author(id, first_name, last_name) values(2, 'Marcel', 'Proust');
insert into author(id, first_name, last_name) values(3, 'Franz', 'Kafka');
insert into author(id, first_name, last_name) values(4, 'Antoine', 'de Saint-Exupéry');
insert into author(id, first_name, last_name) values(5, 'André', 'Malraux');
insert into author(id, first_name, last_name) values(6, 'Louis-Ferdinand', 'Céline');
insert into author(id, first_name, last_name) values(7, 'John', 'Steinbeck');
insert into author(id, first_name, last_name) values(8, 'Ernest', 'Hemingway');
insert into author(id, first_name, last_name) values(9, 'Alain', 'Fournier');
insert into author(id, first_name, last_name) values(10, 'Boris', 'Vian');
insert into author(id, first_name, last_name) values(11, 'Simone', 'de Beauvoir');
insert into author(id, first_name, last_name) values(12, 'Samuel', 'Beckett');
insert into author(id, first_name, last_name) values(13, 'Jean-Paul', 'Sartre');
insert into author(id, first_name, last_name) values(14, 'Umberto', 'Eco');
insert into author(id, first_name, last_name) values(15, 'Aleksandr', 'Solzhenitsyn');
insert into author(id, first_name, last_name) values(16, 'Jacques', 'Prévert');
insert into author(id, first_name, last_name) values(17, 'Guillaume', 'Apollinaire');
insert into author(id, first_name, last_name) values(18, 'Georges', 'Remi');
insert into author(id, first_name, last_name) values(19, 'Anne', 'Frank');
insert into author(id, first_name, last_name) values(20, 'Claude', 'Lévi-Strauss');
insert into author(id, first_name, last_name) values(21, 'Aldous', 'Huxley');
insert into author(id, first_name, last_name) values(22, 'George', 'Orwell');
insert into author(id, first_name, last_name) values(23, 'René', 'Goscinny');
insert into author(id, first_name, last_name) values(24, 'Eugène', 'Ionesco');
insert into author(id, first_name, last_name) values(25, 'Sigmund', 'Freud');
insert into author(id, first_name, last_name) values(26, 'Marguerite', 'Yourcenar');
insert into author(id, first_name, last_name) values(27, 'Vladimir', 'Nabokov');
insert into author(id, first_name, last_name) values(28, 'James', 'Joyce');
insert into author(id, first_name, last_name) values(29, 'Dino', 'Buzzati');
insert into author(id, first_name, last_name) values(30, 'André', 'Gide');
insert into author(id, first_name, last_name) values(31, 'Jean', 'Giono');
insert into author(id, first_name, last_name) values(32, 'Albert', 'Cohen');
insert into author(id, first_name, last_name) values(33, 'Gabriel', 'Márquez');
insert into author(id, first_name, last_name) values(34, 'William', 'Faulkner');
insert into author(id, first_name, last_name) values(35, 'François', 'Mauriac');
insert into author(id, first_name, last_name) values(36, 'Raymond', 'Queneau');
insert into author(id, first_name, last_name) values(37, 'Stefan', 'Zweig');
insert into author(id, first_name, last_name) values(38, 'Margaret', 'Mitchell');
insert into author(id, first_name, last_name) values(39, 'David', 'Lawrence');
insert into author(id, first_name, last_name) values(40, 'Thomas', 'Mann');
insert into author(id, first_name, last_name) values(41, 'Françoise', 'Sagan');
insert into author(id, first_name, last_name) values(42, 'Jean', 'Bruller');
insert into author(id, first_name, last_name) values(43, 'Georges', 'Perec');
insert into author(id, first_name, last_name) values(44, 'Arthur', 'Doyle');
insert into author(id, first_name, last_name) values(45, 'Georges', 'Bernanos');
insert into author(id, first_name, last_name) values(46, 'Francis', 'Fitzgerald');
insert into author(id, first_name, last_name) values(47, 'Milan', 'Kundera');
insert into author(id, first_name, last_name) values(48, 'Alberto', 'Moravia');
insert into author(id, first_name, last_name) values(49, 'Agatha', 'Christie');
insert into author(id, first_name, last_name) values(50, 'André', 'Breton');
insert into author(id, first_name, last_name) values(51, 'Louis', 'Aragon');
insert into author(id, first_name, last_name) values(52, 'Paul', 'Claudel');
insert into author(id, first_name, last_name) values(53, 'Luigi', 'Pirandello');
insert into author(id, first_name, last_name) values(54, 'Bertolt', 'Brecht');
insert into author(id, first_name, last_name) values(55, 'Michel', 'Tournier');
insert into author(id, first_name, last_name) values(56, 'Herbert', 'Wells');
insert into author(id, first_name, last_name) values(57, 'Primo', 'Levi');
insert into author(id, first_name, last_name) values(58, 'John', 'Tolkien');
insert into author(id, first_name, last_name) values(59, 'Sidonie', 'Colette');
insert into author(id, first_name, last_name) values(60, 'Paul', 'Éluard');
insert into author(id, first_name, last_name) values(61, 'Jack', 'London');
insert into author(id, first_name, last_name) values(62, 'Hugo', 'Pratt');
insert into author(id, first_name, last_name) values(63, 'Roland', 'Barthes');
insert into author(id, first_name, last_name) values(64, 'Heinrich', 'Böll');
insert into author(id, first_name, last_name) values(65, 'Julien', 'Gracq');
insert into author(id, first_name, last_name) values(66, 'Michel', 'Foucault');
insert into author(id, first_name, last_name) values(67, 'Jack', 'Kerouac');
insert into author(id, first_name, last_name) values(68, 'Selma', 'Lagerlöf');
insert into author(id, first_name, last_name) values(69, 'Virginia', 'Woolf');
insert into author(id, first_name, last_name) values(70, 'Ray', 'Bradbury');
insert into author(id, first_name, last_name) values(71, 'Marguerite', 'Duras');
insert into author(id, first_name, last_name) values(72, 'Jean Marie', 'Le Clézio');
insert into author(id, first_name, last_name) values(73, 'Nathalie', 'Sarraute');
insert into author(id, first_name, last_name) values(74, 'Jules', 'Renard');
insert into author(id, first_name, last_name) values(75, 'Joseph', 'Conrad');
insert into author(id, first_name, last_name) values(76, 'Jacques', 'Lacan');
insert into author(id, first_name, last_name) values(77, 'Antonin', 'Artaud');
insert into author(id, first_name, last_name) values(78, 'John', 'Passos');
insert into author(id, first_name, last_name) values(79, 'Jorge', 'Borges');
insert into author(id, first_name, last_name) values(80, 'Blaise', 'Cendrars');
insert into author(id, first_name, last_name) values(81, 'Ismail', 'Kadare');
insert into author(id, first_name, last_name) values(82, 'William', 'Styron');
insert into author(id, first_name, last_name) values(83, 'Federico', 'Lorca');
insert into author(id, first_name, last_name) values(84, 'Georges', 'Simenon');
insert into author(id, first_name, last_name) values(85, 'Jean', 'Genet');
insert into author(id, first_name, last_name) values(86, 'Robert', 'Musil');
insert into author(id, first_name, last_name) values(87, 'René', 'Char');
insert into author(id, first_name, last_name) values(88, 'Jerome', 'Salinger');
insert into author(id, first_name, last_name) values(89, 'James', 'Chase');
insert into author(id, first_name, last_name) values(90, 'Edgar', 'Jacobs');
insert into author(id, first_name, last_name) values(91, 'Rainer', 'Rilke');
insert into author(id, first_name, last_name) values(92, 'Michel', 'Butor');
insert into author(id, first_name, last_name) values(93, 'Hannah', 'Arendt');
insert into author(id, first_name, last_name) values(94, 'Mikhail', 'Bulgakov');
insert into author(id, first_name, last_name) values(95, 'Henry', 'Miller');
insert into author(id, first_name, last_name) values(96, 'Raymond', 'Chandler');
insert into author(id, first_name, last_name) values(97, 'Saint-John', 'Perse');
insert into author(id, first_name, last_name) values(98, 'André', 'Franquin');
insert into author(id, first_name, last_name) values(99, 'Malcolm', 'Lowry');
insert into author(id, first_name, last_name) values(100, 'Salman', 'Rushdie');

insert into book(id, title, year, language) values(1,'The Stranger',1942,'French');
insert into book(id, title, year, language) values(2,'In Search of Lost Time',1927,'French');
insert into book(id, title, year, language) values(3,'The Trial',1925,'German');
insert into book(id, title, year, language) values(4,'The Little Prince',1943,'French');
insert into book(id, title, year, language) values(5,'Man''s Fate',1933,'French');
insert into book(id, title, year, language) values(6,'Journey to the End of the Night',1932,'French');
insert into book(id, title, year, language) values(7,'The Grapes of Wrath',1939,'English');
insert into book(id, title, year, language) values(8,'For Whom the Bell Tolls',1940,'English');
insert into book(id, title, year, language) values(9,'Le Grand Meaulnes',1913,'French');
insert into book(id, title, year, language) values(10,'Froth on the Daydream',1947,'French');
insert into book(id, title, year, language) values(11,'The Second Sex',1949,'French');
insert into book(id, title, year, language) values(12,'Waiting for Godot',1952,'French');
insert into book(id, title, year, language) values(13,'Being and Nothingness',1943,'French');
insert into book(id, title, year, language) values(14,'The Name of the Rose',1980,'Italian');
insert into book(id, title, year, language) values(15,'The Gulag Archipelago',1973,'Russian');
insert into book(id, title, year, language) values(16,'Paroles',1946,'French');
insert into book(id, title, year, language) values(17,'Alcools',1913,'French');
insert into book(id, title, year, language) values(18,'The Blue Lotus',1936,'French');
insert into book(id, title, year, language) values(19,'The Diary of a Young Girl',1947,'Dutch');
insert into book(id, title, year, language) values(20,'Tristes Tropiques',1955,'French');
insert into book(id, title, year, language) values(21,'Brave New World',1932,'English');
insert into book(id, title, year, language) values(22,'Nineteen Eighty-Four',1949,'English');
insert into book(id, title, year, language) values(23,'Asterix the Gaul',1959,'French');
insert into book(id, title, year, language) values(24,'The Bald Soprano',1952,'French');
insert into book(id, title, year, language) values(25,'Three Essays on the Theory of Sexuality',1905,'German');
insert into book(id, title, year, language) values(26,'The Abyss',1968,'French');
insert into book(id, title, year, language) values(27,'Lolita',1955,'English');
insert into book(id, title, year, language) values(28,'Ulysses',1922,'English');
insert into book(id, title, year, language) values(29,'The Tartar Steppe',1940,'Italian');
insert into book(id, title, year, language) values(30,'The Counterfeiters',1925,'French');
insert into book(id, title, year, language) values(31,'The Horseman on the Roof',1951,'French');
insert into book(id, title, year, language) values(32,'Belle du Seigneur',1968,'French');
insert into book(id, title, year, language) values(33,'One Hundred Years of Solitude',1967,'Spanish');
insert into book(id, title, year, language) values(34,'The Sound and the Fury',1929,'English');
insert into book(id, title, year, language) values(35,'Thérèse Desqueyroux',1927,'French');
insert into book(id, title, year, language) values(36,'Zazie in the Metro',1959,'French');
insert into book(id, title, year, language) values(37,'Confusion of Feelings',1927,'German');
insert into book(id, title, year, language) values(38,'Gone with the Wind',1936,'English');
insert into book(id, title, year, language) values(39,'Lady Chatterley''s Lover',1928,'English');
insert into book(id, title, year, language) values(40,'The Magic Mountain',1924,'German');
insert into book(id, title, year, language) values(41,'Bonjour Tristesse',1954,'French');
insert into book(id, title, year, language) values(42,'Le Silence de la mer',1942,'French');
insert into book(id, title, year, language) values(43,'Life: A User''s Manual',1978,'French');
insert into book(id, title, year, language) values(44,'The Hound of the Baskervilles',1902,'English');
insert into book(id, title, year, language) values(45,'Under the Sun of Satan',1926,'French');
insert into book(id, title, year, language) values(46,'The Great Gatsby',1925,'English');
insert into book(id, title, year, language) values(47,'The Joke',1967,'Czech');
insert into book(id, title, year, language) values(48,'Contempt/A Ghost at Noon',1954,'Italian');
insert into book(id, title, year, language) values(49,'The Murder of Roger Ackroyd',1926,'English');
insert into book(id, title, year, language) values(50,'Nadja',1928,'French');
insert into book(id, title, year, language) values(51,'Aurélien',1944,'French');
insert into book(id, title, year, language) values(52,'The Satin Slipper',1929,'French');
insert into book(id, title, year, language) values(53,'Six Characters in Search of an Author',1921,'Italian');
insert into book(id, title, year, language) values(54,'The Resistible Rise of Arturo Ui',1941,'German');
insert into book(id, title, year, language) values(55,'Friday',1967,'French');
insert into book(id, title, year, language) values(56,'The War of the Worlds',1898,'English');
insert into book(id, title, year, language) values(57,'If This Is a Man',1947,'Italian');
insert into book(id, title, year, language) values(58,'The Lord of the Rings',1955,'English');
insert into book(id, title, year, language) values(59,'Les Vrilles de la vigne',1908,'French');
insert into book(id, title, year, language) values(60,'Capital of Pain',1926,'French');
insert into book(id, title, year, language) values(61,'Martin Eden',1909,'English');
insert into book(id, title, year, language) values(62,'Ballad of the Salt Sea',1967,'Italian');
insert into book(id, title, year, language) values(63,'Writing Degree Zero',1953,'French');
insert into book(id, title, year, language) values(64,'The Lost Honour of Katharina Blum',1974,'German');
insert into book(id, title, year, language) values(65,'The Opposing Shore',1951,'French');
insert into book(id, title, year, language) values(66,'The Order of Things',1966,'French');
insert into book(id, title, year, language) values(67,'On the Road',1957,'English');
insert into book(id, title, year, language) values(68,'The Wonderful Adventures of Nils',1907,'Swedish');
insert into book(id, title, year, language) values(69,'A Room of One''s Own',1929,'English');
insert into book(id, title, year, language) values(70,'The Martian Chronicles',1950,'English');
insert into book(id, title, year, language) values(71,'The Ravishing of Lol Stein',1964,'French');
insert into book(id, title, year, language) values(72,'The Interrogation',1963,'French');
insert into book(id, title, year, language) values(73,'Tropisms',1939,'French');
insert into book(id, title, year, language) values(74,'Journal, 1887–1910',1925,'French');
insert into book(id, title, year, language) values(75,'Lord Jim',1900,'English');
insert into book(id, title, year, language) values(76,'Écrits',1966,'French');
insert into book(id, title, year, language) values(77,'The Theatre and its Double',1938,'French');
insert into book(id, title, year, language) values(78,'Manhattan Transfer',1925,'English');
insert into book(id, title, year, language) values(79,'Ficciones',1944,'Spanish');
insert into book(id, title, year, language) values(80,'Moravagine',1926,'French');
insert into book(id, title, year, language) values(81,'The General of the Dead Army',1963,'Albanian');
insert into book(id, title, year, language) values(82,'Sophie''s Choice',1979,'English');
insert into book(id, title, year, language) values(83,'Gypsy Ballads',1928,'Spanish');
insert into book(id, title, year, language) values(84,'The Strange Case of Peter the Lett',1931,'French');
insert into book(id, title, year, language) values(85,'Our Lady of the Flowers',1944,'French');
insert into book(id, title, year, language) values(86,'The Man Without Qualities',1942,'German');
insert into book(id, title, year, language) values(87,'Furor and Mystery',1948,'French');
insert into book(id, title, year, language) values(88,'The Catcher in the Rye',1951,'English');
insert into book(id, title, year, language) values(89,'No Orchids For Miss Blandish',1939,'English');
insert into book(id, title, year, language) values(90,'Blake and Mortimer',1950,'French');
insert into book(id, title, year, language) values(91,'The Notebooks of Malte Laurids Brigge',1910,'German');
insert into book(id, title, year, language) values(92,'Second Thoughts',1957,'French');
insert into book(id, title, year, language) values(93,'The Origins of Totalitarianism',1951,'English');
insert into book(id, title, year, language) values(94,'The Master and Margarita',1967,'Russian');
insert into book(id, title, year, language) values(95,'The Rosy Crucifixion',1960,'English');
insert into book(id, title, year, language) values(96,'The Big Sleep',1939,'English');
insert into book(id, title, year, language) values(97,'Amers',1957,'French');
insert into book(id, title, year, language) values(98,'Gaston',1957,'French');
insert into book(id, title, year, language) values(99,'Under the Volcano',1947,'English');
insert into book(id, title, year, language) values(100,'Midnight''s Children',1981,'English');
