INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(1, 'The Stranger', 'Albert', 'Camus',	1942, 'French');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(2, 'In Search of Lost Time', 'Marcel', 'Proust',	1927, 'French');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(3, 'The Trial', 'Franz', 'Kafka',	1925, 'German');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(4, 'The Little Prince', 'Antoine', 'Saint-Exupéry', 1943, 'French');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(5, 'Man''s fate', 'André', 'Malraux', 1933, 'French');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(6, 'Journey to the End of the Night', 'Louis-Ferdinand', 'Céline', 1932, 'French');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(7, 'The Grapes of Wrath', 'John', 'Steinbeck', 1939, 'English');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(8, 'For Whom the Bell Tolls', 'Ernest', 'Hemingway', 1940, 'English');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(9, 'Le Grand Meaulnes', 'Alain', 'Fournier', 1913, 'French');
INSERT INTO BOOK(position, title, lastname, firstname, year, language) values(10, 'Froth on the Daydream', 'Boris', 'Vian', 1947, 'French');